name: CodeCov
'on':
  - push
  - pull_request
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    environment:
      name: CodeCov
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: ‘2’
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m unittest discover tests
      - name: Upload Coverage to Codecov
        run: |
          pip install codecov
          codecov -t ${{ secrets.CODECOV_TOKEN }}
